// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import type { LocalizedString } from 'typesafe-i18n'

export type BaseLocale = 'en'

export type Locales =
	| 'en'
	| 'ja'

export type Translation = {
	/**
	 * app started (EN)
	 */
	'STARTUP': string
	/**
	 * Subatomos - Oozora Subaru Fansite
	 */
	'TITLE': string
	'HOME': {	
		/**
		 * Subatomos Projects
		 */
		'PROJECTS': string
		/**
		 * 3rd anniversary
		 */
		'THIRD_ANNIVERSARY': string
		/**
		 * 1 million subscribers & birthday
		 */
		'BIRTHDAY': string
		/**
		 * 2nd anniversary
		 */
		'SECOND_ANNIVERSARY': string
		/**
		 * SOUNDBOARD
		 */
		'SOUNDBOARD': string
	}
	'HEADER': {	
		/**
		 * HOME
		 */
		'HOME': string
		/**
		 * PROJECTS
		 */
		'PROJECTS': string
		/**
		 * SUBATOMO PONDS
		 */
		'PONDS': string
		/**
		 * SOUNDBOARD
		 */
		'SOUNDBOARD': string
		/**
		 * 3RD ANNIVERSARY
		 */
		'THIRD_ANNIVERSARY': string
	}
	'THIRD': {	
		/**
		 * Subaru's 3rd anniversary!
		 */
		'TITLE': string
		/**
		 * Congratulations on your third anniversary, Subaru!
		 */
		'CONGRATS': string
		/**
		 * Credits
		 */
		'CREDITS': string
		/**
		 * Animation
		 */
		'ANIMATION': string
		/**
		 * Messages & Fanart
		 */
		'MESSAGES': string
		/**
		 * Show/hide only fanart
		 */
		'FANART_ONLY': string
		'A': {	
			/**
			 * Original Outfit
			 */
			'ONE': string
			/**
			 * Sailor Outfit
			 */
			'TWO': string
			/**
			 * Swimsuit
			 */
			'THREE': string
			/**
			 * New Year's Kimono
			 */
			'FOUR': string
			/**
			 * Idol Outfit
			 */
			'FIVE': string
			/**
			 * Girly Outfit
			 */
			'SIX': string
		}
		/**
		 * Music
		 */
		'MUSIC': string
		'M': {	
			/**
			 * Daily Diary
			 */
			'DD': string
			/**
			 * Dreaming Days
			 */
			'DrD': string
			/**
			 * Koi no Mahou
			 */
			'KNM': string
			/**
			 * Taiyou Shoujo
			 */
			'TS': string
			/**
			 * Do my Best!
			 */
			'DMB': string
			/**
			 * Kirameki Rider
			 */
			'KR': string
			/**
			 * Natsu Aji!!
			 */
			'NA': string
			/**
			 * Orchestral
			 */
			'ORCHESTRAL': string
			/**
			 * Oozora Kensetsu Theme
			 */
			'KENSETSU': string
		}
		/**
		 * Editing
		 */
		'EDITING': string
		/**
		 * Translation
		 */
		'TRANSLATION': string
		/**
		 * Direction
		 */
		'DIRECTION': string
		/**
		 * Storyboard
		 */
		'STORYBOARD': string
		/**
		 * Subatomo Logo
		 */
		'LOGO_SUBA': string
		/**
		 * Project Logo
		 */
		'LOGO_PROJ': string
		/**
		 * Special Thanks
		 */
		'THANKS': string
	}
}

export type TranslationFunctions = {
	/**
	 * app started (EN)
	 */
	'STARTUP': () => LocalizedString
	/**
	 * Subatomos - Oozora Subaru Fansite
	 */
	'TITLE': () => LocalizedString
	'HOME': {	
		/**
		 * Subatomos Projects
		 */
		'PROJECTS': () => LocalizedString
		/**
		 * 3rd anniversary
		 */
		'THIRD_ANNIVERSARY': () => LocalizedString
		/**
		 * 1 million subscribers & birthday
		 */
		'BIRTHDAY': () => LocalizedString
		/**
		 * 2nd anniversary
		 */
		'SECOND_ANNIVERSARY': () => LocalizedString
		/**
		 * SOUNDBOARD
		 */
		'SOUNDBOARD': () => LocalizedString
	}
	'HEADER': {	
		/**
		 * HOME
		 */
		'HOME': () => LocalizedString
		/**
		 * PROJECTS
		 */
		'PROJECTS': () => LocalizedString
		/**
		 * SUBATOMO PONDS
		 */
		'PONDS': () => LocalizedString
		/**
		 * SOUNDBOARD
		 */
		'SOUNDBOARD': () => LocalizedString
		/**
		 * 3RD ANNIVERSARY
		 */
		'THIRD_ANNIVERSARY': () => LocalizedString
	}
	'THIRD': {	
		/**
		 * Subaru's 3rd anniversary!
		 */
		'TITLE': () => LocalizedString
		/**
		 * Congratulations on your third anniversary, Subaru!
		 */
		'CONGRATS': () => LocalizedString
		/**
		 * Credits
		 */
		'CREDITS': () => LocalizedString
		/**
		 * Animation
		 */
		'ANIMATION': () => LocalizedString
		/**
		 * Messages & Fanart
		 */
		'MESSAGES': () => LocalizedString
		/**
		 * Show/hide only fanart
		 */
		'FANART_ONLY': () => LocalizedString
		'A': {	
			/**
			 * Original Outfit
			 */
			'ONE': () => LocalizedString
			/**
			 * Sailor Outfit
			 */
			'TWO': () => LocalizedString
			/**
			 * Swimsuit
			 */
			'THREE': () => LocalizedString
			/**
			 * New Year's Kimono
			 */
			'FOUR': () => LocalizedString
			/**
			 * Idol Outfit
			 */
			'FIVE': () => LocalizedString
			/**
			 * Girly Outfit
			 */
			'SIX': () => LocalizedString
		}
		/**
		 * Music
		 */
		'MUSIC': () => LocalizedString
		'M': {	
			/**
			 * Daily Diary
			 */
			'DD': () => LocalizedString
			/**
			 * Dreaming Days
			 */
			'DrD': () => LocalizedString
			/**
			 * Koi no Mahou
			 */
			'KNM': () => LocalizedString
			/**
			 * Taiyou Shoujo
			 */
			'TS': () => LocalizedString
			/**
			 * Do my Best!
			 */
			'DMB': () => LocalizedString
			/**
			 * Kirameki Rider
			 */
			'KR': () => LocalizedString
			/**
			 * Natsu Aji!!
			 */
			'NA': () => LocalizedString
			/**
			 * Orchestral
			 */
			'ORCHESTRAL': () => LocalizedString
			/**
			 * Oozora Kensetsu Theme
			 */
			'KENSETSU': () => LocalizedString
		}
		/**
		 * Editing
		 */
		'EDITING': () => LocalizedString
		/**
		 * Translation
		 */
		'TRANSLATION': () => LocalizedString
		/**
		 * Direction
		 */
		'DIRECTION': () => LocalizedString
		/**
		 * Storyboard
		 */
		'STORYBOARD': () => LocalizedString
		/**
		 * Subatomo Logo
		 */
		'LOGO_SUBA': () => LocalizedString
		/**
		 * Project Logo
		 */
		'LOGO_PROJ': () => LocalizedString
		/**
		 * Special Thanks
		 */
		'THANKS': () => LocalizedString
	}
}

export type Formatters = {}
