// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import type { LocalizedString } from 'typesafe-i18n';

export type BaseLocale = 'en';

export type Locales = 'en' | 'it' | 'ja';

export type Translation = {
	/**
	 * app started (EN)
	 */
	STARTUP: string;
	/**
	 * Subatomos - Oozora Subaru Fansite
	 */
	TITLE: string;
	HOME: {
		/**
		 * A website by overseas fans showcasing community projects celebrating Oozora Subaru!
		 */
		META_DESC: string;
		/**
		 * Subatomos Projects
		 */
		PROJECTS: string;
		/**
		 * 3rd anniversary
		 */
		THIRD_ANNIVERSARY: string;
		/**
		 * 1 million subscribers & birthday
		 */
		BIRTHDAY: string;
		/**
		 * 1M subscribers & birthday
		 */
		BIRTHDAY_SM: string;
		/**
		 * 2nd anniversary
		 */
		SECOND_ANNIVERSARY: string;
		/**
		 * Soundboard
		 */
		SOUNDBOARD: string;
	};
	HEADER: {
		/**
		 * HOME
		 */
		HOME: string;
		/**
		 * PROJECTS
		 */
		PROJECTS: string;
		/**
		 * SUBATOMO PONDS
		 */
		PONDS: string;
		/**
		 * SOUNDBOARD
		 */
		SOUNDBOARD: string;
		/**
		 * 3RD ANNIVERSARY
		 */
		THIRD_ANNIVERSARY: string;
	};
	THIRD: {
		/**
		 * Subatomos' project to celebrate Subaru's 3rd debut anniversary! Featuring an animated video with remixes and cover songs created by the community.
		 */
		META_DESC: string;
		/**
		 * Subaru's 3rd anniversary!
		 */
		TITLE: string;
		/**
		 * Congratulations on your third anniversary, Subaru!
		 */
		CONGRATS: string;
		/**
		 * Credits
		 */
		CREDITS: string;
		/**
		 * Animation
		 */
		ANIMATION: string;
		/**
		 * Messages & Fanart
		 */
		MESSAGES: string;
		/**
		 * Show/hide only fanart
		 */
		FANART_ONLY: string;
		/**
		 * Back to top
		 */
		BACK_TO_TOP: string;
		A: {
			/**
			 * Original Outfit
			 */
			ONE: string;
			/**
			 * School Uniform Style Idol
			 */
			TWO: string;
			/**
			 * Swimsuit
			 */
			THREE: string;
			/**
			 * New Year's Kimono
			 */
			FOUR: string;
			/**
			 * 3D LIVE Idol
			 */
			FIVE: string;
			/**
			 * Girly Outfit
			 */
			SIX: string;
		};
		/**
		 * Music
		 */
		MUSIC: string;
		M: {
			/**
			 * Daily Diary
			 */
			DD: string;
			/**
			 * Dreaming Days
			 */
			DrD: string;
			/**
			 * Koi no Mahou
			 */
			KNM: string;
			/**
			 * Taiyou Shoujo
			 */
			TS: string;
			/**
			 * Do my Best!
			 */
			DMB: string;
			/**
			 * Kirameki Rider
			 */
			KR: string;
			/**
			 * Natsu Aji!!
			 */
			NA: string;
			/**
			 * Orchestral
			 */
			ORCHESTRAL: string;
			/**
			 * Oozora Kensetsu Theme
			 */
			KENSETSU: string;
		};
		/**
		 * Editing
		 */
		EDITING: string;
		/**
		 * Translation
		 */
		TRANSLATION: string;
		/**
		 * Direction
		 */
		DIRECTION: string;
		/**
		 * Storyboard
		 */
		STORYBOARD: string;
		/**
		 * Subatomo Logo
		 */
		LOGO_SUBA: string;
		/**
		 * Project Logo
		 */
		LOGO_PROJ: string;
		/**
		 * Special Thanks
		 */
		THANKS: string;
	};
	PONDS: {
		/**
		 * Subatomos' project to celebrate Subaru's birthday & 1M subscribers milestone, with over 2000 duck submissions from fans!
		 */
		META_DESC: string;
		/**
		 * Subatomo Ponds
		 */
		TITLE: string;
		/**
		 * 1 million subscribers & birthday project
		 */
		SUBTITLE: string;
		/**
		 * Visit the site here!
		 */
		VISIT: string;
		/**
		 * We surveyed users during their submissions. These are the results:
		 */
		GRAPHS: string;
	};
	SOUNDBOARD: {
		/**
		 * To suggest a sound to add, please contact us in any of these places:
		 */
		SUGGEST: string;
	};
	WIKI: {
		/**
		 * Categories
		 */
		CATEGORIES: string;
		/**
		 * Recently Updated
		 */
		RECENT_POSTS: string;
		/**
		 * Recurring jokes/memes
		 */
		JOKES: string;
		/**
		 * Groups
		 */
		GROUPS: string;
	};
};

export type TranslationFunctions = {
	/**
	 * app started (EN)
	 */
	STARTUP: () => LocalizedString;
	/**
	 * Subatomos - Oozora Subaru Fansite
	 */
	TITLE: () => LocalizedString;
	HOME: {
		/**
		 * A website by overseas fans showcasing community projects celebrating Oozora Subaru!
		 */
		META_DESC: () => LocalizedString;
		/**
		 * Subatomos Projects
		 */
		PROJECTS: () => LocalizedString;
		/**
		 * 3rd anniversary
		 */
		THIRD_ANNIVERSARY: () => LocalizedString;
		/**
		 * 1 million subscribers & birthday
		 */
		BIRTHDAY: () => LocalizedString;
		/**
		 * 1M subscribers & birthday
		 */
		BIRTHDAY_SM: () => LocalizedString;
		/**
		 * 2nd anniversary
		 */
		SECOND_ANNIVERSARY: () => LocalizedString;
		/**
		 * Soundboard
		 */
		SOUNDBOARD: () => LocalizedString;
	};
	HEADER: {
		/**
		 * HOME
		 */
		HOME: () => LocalizedString;
		/**
		 * PROJECTS
		 */
		PROJECTS: () => LocalizedString;
		/**
		 * SUBATOMO PONDS
		 */
		PONDS: () => LocalizedString;
		/**
		 * SOUNDBOARD
		 */
		SOUNDBOARD: () => LocalizedString;
		/**
		 * 3RD ANNIVERSARY
		 */
		THIRD_ANNIVERSARY: () => LocalizedString;
	};
	THIRD: {
		/**
		 * Subatomos' project to celebrate Subaru's 3rd debut anniversary! Featuring an animated video with remixes and cover songs created by the community.
		 */
		META_DESC: () => LocalizedString;
		/**
		 * Subaru's 3rd anniversary!
		 */
		TITLE: () => LocalizedString;
		/**
		 * Congratulations on your third anniversary, Subaru!
		 */
		CONGRATS: () => LocalizedString;
		/**
		 * Credits
		 */
		CREDITS: () => LocalizedString;
		/**
		 * Animation
		 */
		ANIMATION: () => LocalizedString;
		/**
		 * Messages & Fanart
		 */
		MESSAGES: () => LocalizedString;
		/**
		 * Show/hide only fanart
		 */
		FANART_ONLY: () => LocalizedString;
		/**
		 * Back to top
		 */
		BACK_TO_TOP: () => LocalizedString;
		A: {
			/**
			 * Original Outfit
			 */
			ONE: () => LocalizedString;
			/**
			 * School Uniform Style Idol
			 */
			TWO: () => LocalizedString;
			/**
			 * Swimsuit
			 */
			THREE: () => LocalizedString;
			/**
			 * New Year's Kimono
			 */
			FOUR: () => LocalizedString;
			/**
			 * 3D LIVE Idol
			 */
			FIVE: () => LocalizedString;
			/**
			 * Girly Outfit
			 */
			SIX: () => LocalizedString;
		};
		/**
		 * Music
		 */
		MUSIC: () => LocalizedString;
		M: {
			/**
			 * Daily Diary
			 */
			DD: () => LocalizedString;
			/**
			 * Dreaming Days
			 */
			DrD: () => LocalizedString;
			/**
			 * Koi no Mahou
			 */
			KNM: () => LocalizedString;
			/**
			 * Taiyou Shoujo
			 */
			TS: () => LocalizedString;
			/**
			 * Do my Best!
			 */
			DMB: () => LocalizedString;
			/**
			 * Kirameki Rider
			 */
			KR: () => LocalizedString;
			/**
			 * Natsu Aji!!
			 */
			NA: () => LocalizedString;
			/**
			 * Orchestral
			 */
			ORCHESTRAL: () => LocalizedString;
			/**
			 * Oozora Kensetsu Theme
			 */
			KENSETSU: () => LocalizedString;
		};
		/**
		 * Editing
		 */
		EDITING: () => LocalizedString;
		/**
		 * Translation
		 */
		TRANSLATION: () => LocalizedString;
		/**
		 * Direction
		 */
		DIRECTION: () => LocalizedString;
		/**
		 * Storyboard
		 */
		STORYBOARD: () => LocalizedString;
		/**
		 * Subatomo Logo
		 */
		LOGO_SUBA: () => LocalizedString;
		/**
		 * Project Logo
		 */
		LOGO_PROJ: () => LocalizedString;
		/**
		 * Special Thanks
		 */
		THANKS: () => LocalizedString;
	};
	PONDS: {
		/**
		 * Subatomos' project to celebrate Subaru's birthday & 1M subscribers milestone, with over 2000 duck submissions from fans!
		 */
		META_DESC: () => LocalizedString;
		/**
		 * Subatomo Ponds
		 */
		TITLE: () => LocalizedString;
		/**
		 * 1 million subscribers & birthday project
		 */
		SUBTITLE: () => LocalizedString;
		/**
		 * Visit the site here!
		 */
		VISIT: () => LocalizedString;
		/**
		 * We surveyed users during their submissions. These are the results:
		 */
		GRAPHS: () => LocalizedString;
	};
	SOUNDBOARD: {
		/**
		 * To suggest a sound to add, please contact us in any of these places:
		 */
		SUGGEST: () => LocalizedString;
	};
	WIKI: {
		/**
		 * Categories
		 */
		CATEGORIES: () => LocalizedString;
		/**
		 * Recently Updated
		 */
		RECENT_POSTS: () => LocalizedString;
		/**
		 * Recurring jokes/memes
		 */
		JOKES: () => LocalizedString;
		/**
		 * Groups
		 */
		GROUPS: () => LocalizedString;
	};
};

export type Formatters = {};
