// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */

import type { LocalizedString } from 'typesafe-i18n';

export type BaseLocale = 'en';

export type Locales = 'en' | 'ja';

export type Translation = {
	/**
	 * app started (EN)
	 */
	STARTUP: string;
	/**
	 * Subatomos - Oozora Subaru Fansite
	 */
	TITLE: string;
	/**
	 * Main page in development
	 */
	IN_DEV: string;
	HEADER: {
		/**
		 * HOME
		 */
		HOME: string;
		/**
		 * PROJECTS
		 */
		PROJECTS: string;
		/**
		 * SUBATOMO PONDS
		 */
		PONDS: string;
		/**
		 * SOUNDBOARD
		 */
		SOUNDBOARD: string;
		/**
		 * 3RD ANNIVERSARY
		 */
		THIRD_ANNIVERSARY: string;
	};
};

export type TranslationFunctions = {
	/**
	 * app started (EN)
	 */
	STARTUP: () => LocalizedString;
	/**
	 * Subatomos - Oozora Subaru Fansite
	 */
	TITLE: () => LocalizedString;
	/**
	 * Main page in development
	 */
	IN_DEV: () => LocalizedString;
	HEADER: {
		/**
		 * HOME
		 */
		HOME: () => LocalizedString;
		/**
		 * PROJECTS
		 */
		PROJECTS: () => LocalizedString;
		/**
		 * SUBATOMO PONDS
		 */
		PONDS: () => LocalizedString;
		/**
		 * SOUNDBOARD
		 */
		SOUNDBOARD: () => LocalizedString;
		/**
		 * 3RD ANNIVERSARY
		 */
		THIRD_ANNIVERSARY: () => LocalizedString;
	};
};

export type Formatters = {};
